language: scala
scala:
    - 2.10.5
    - 2.11.11
    - 2.12.2
jdk:
    - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test tut doc
  - (cd example ; sbt ++$TRAVIS_SCALA_VERSION test)

  # check if there are no changes after `tut` runs
  - if [[ $TRAVIS_SCALA_VERSION =~ '^2\.12.*' ]]; then
      git diff --exit-code;
      fi
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls
cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt/boot
