language: scala
scala:
    - 2.10.5
    - 2.11.8
    - 2.12.1
jdk:
    - oraclejdk8
script:
  - sbt ++$TRAVIS_SCALA_VERSION coverage test tut
  - (cd example ; sbt ++$TRAVIS_SCALA_VERSION test)

  # check if there are no changes after `tut` runs
  - if [[ $TRAVIS_SCALA_VERSION =~ '^2\.12.*' ]]; then
      git diff --exit-code;
      fi
after_success:
  - sbt ++$TRAVIS_SCALA_VERSION coverageReport coverageAggregate coveralls
