sudo: false
language: scala

scala:
  - 2.10.6
  - 2.11.11
  - 2.12.4
jdk:
  - oraclejdk8
env:
  # marker environment variable to make the build matrix more readable in the UI
  - JOB=test

script:
  - sbt coverage "+++$TRAVIS_SCALA_VERSION test" "+++$TRAVIS_SCALA_VERSION tut" "+++$TRAVIS_SCALA_VERSION doc"
  - (cd example ; sbt ++$TRAVIS_SCALA_VERSION test)

  # check if there are no changes after `tut` runs
  - if [[ $TRAVIS_SCALA_VERSION =~ ^2\.12.* ]]; then
      git diff --exit-code;
      fi

after_success:
  - sbt ++$TRAVIS_SCALA_VERSION "+++$TRAVIS_SCALA_VERSION coverageReport" coverageAggregate coveralls

jobs:
  include:
    - env: JOB=microsite
      scala: 2.12.4
      addons:
        apt:
          packages:
            - libcurl4-openssl-dev # required to avoid SSL errors
      before_install:
        - export PATH=${PATH}:./vendor/bundle
        - export NOKOGIRI_USE_SYSTEM_LIBRARIES=true
      install:
        - rvm use 2.4 --install --fuzzy
        - gem update --system
        - gem install sass jekyll:3.2.1 html-proofer
      script:
        - sbt makeMicrosite
          # we're ignoring www.47deg.com due to SSL errors; we should check this again later
        - htmlproofer --allow_hash_href --url-ignore '/www.47deg.com/' docs/target/site
      after_success: ignore

cache:
  directories:
    - $HOME/.ivy2/cache
    - $HOME/.sbt
